//! `cogz init` — initialize `.cogz/` in a repository.
//!
//! Creates the directory structure, generates `config.toml` with
//! defaults (project name autodetected), and generates `.gitignore`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::config;

/// Directories created by `cogz init` inside `.cogz/`.
const SUBDIRS: &[&str] = &["knowledge", "rules", "observations"];

/// Content of the generated `.cogz/.gitignore` (team-sharing mode).
///
/// Paths are relative to `.cogz/` (the .gitignore lives inside it).
/// Knowledge, rules, and observations are committed for team sharing;
/// only the DB is local-only.
const GITIGNORE_CONTENT: &str = "\
# CogZ — generated by cogz init
# Knowledge, rules, and observations are committed (team sharing).
# Only the DB is local-only (disposable, rebuildable from files).
cogz.db
cogz.db-wal
cogz.db-shm
";

/// Content of the generated `.cogz/.gitignore` (local-only mode).
///
/// Ignores everything under `.cogz/` — nothing is committed.
const GITIGNORE_LOCAL_ONLY: &str = "\
# CogZ — generated by cogz init --local-only
# Everything under .cogz/ is local-only — nothing is committed.
*
";

/// Run `cogz init` in the given directory (defaults to current dir).
///
/// - Creates `.cogz/` with subdirectories
/// - Generates `config.toml` with autodetected project name
/// - Generates `.gitignore` for gitignored paths
/// - Refuses to run if `.cogz/` already exists (use `cogz reset` first)
///
/// If `local_only` is true, all of `.cogz/` is gitignored — nothing
/// is committed to git. Use this for solo projects where knowledge,
/// rules, and observations should stay local.
///
/// Returns the success message to print. The caller (CLI) is
/// responsible for printing it.
pub fn run(repo_root: &Path, local_only: bool) -> Result<String> {
    let cogz_dir = repo_root.join(".cogz");

    if cogz_dir.exists() {
        bail!(
            "{} already exists. Use `cogz reset` to remove the DB, \
             or remove .cogz/ manually to reinitialize.",
            cogz_dir.display()
        );
    }

    let project_name = autodetect_project_name(repo_root);

    // Create directory structure
    fs::create_dir_all(&cogz_dir)
        .with_context(|| format!("failed to create {}", cogz_dir.display()))?;
    for subdir in SUBDIRS {
        let path = cogz_dir.join(subdir);
        fs::create_dir_all(&path)
            .with_context(|| format!("failed to create {}", path.display()))?;
    }

    // Generate config.toml
    let config_path = cogz_dir.join("config.toml");
    let config_toml = config::default_toml(&project_name);
    fs::write(&config_path, &config_toml)
        .with_context(|| format!("failed to write {}", config_path.display()))?;

    // Generate .gitignore
    let gitignore_path = cogz_dir.join(".gitignore");
    let gitignore_content = if local_only {
        GITIGNORE_LOCAL_ONLY
    } else {
        GITIGNORE_CONTENT
    };
    fs::write(&gitignore_path, gitignore_content)
        .with_context(|| format!("failed to write {}", gitignore_path.display()))?;

    let sharing_note = if local_only {
        "  sharing:  local-only (all of .cogz/ is gitignored)"
    } else {
        "  sharing:  team (knowledge/, rules/, and observations/ are committed; DB is gitignored)\n  \
         WARNING: knowledge/, rules/, and observations/ are committed to git.\n  \
         Never record secrets, API keys, or credentials in any entity entry."
    };

    Ok(format!(
        "Initialized CogZ in {}\n  project: {}\n  config:  {}\n  gitignore: {}\n{}",
        cogz_dir.display(),
        project_name,
        config_path.display(),
        gitignore_path.display(),
        sharing_note
    ))
}

/// Autodetect the project name.
///
/// 1. Try git remote "origin" URL → extract repo name
/// 2. Fall back to the directory name
fn autodetect_project_name(repo_root: &Path) -> String {
    if let Some(name) = detect_from_git_remote(repo_root) {
        return name;
    }
    detect_from_dir_name(repo_root)
}

/// Extract repo name from git remote "origin" URL.
///
/// `git@github.com:balaianu/CogZ.git` → `CogZ`
/// `https://github.com/balaianu/CogZ.git` → `CogZ`
/// `https://github.com/balaianu/CogZ` → `CogZ`
fn detect_from_git_remote(repo_root: &Path) -> Option<String> {
    let repo = git2::Repository::discover(repo_root).ok()?;
    let remote = repo.find_remote("origin").ok()?;
    let url = remote.url()?;

    // Strip trailing .git
    let url = url.trim_end_matches(".git");

    // Take the last path segment
    let name = url.rsplit('/').next()?;
    let name = name.rsplit(':').next()?; // handle git@host:org/repo format

    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

/// Fall back: use the directory name.
fn detect_from_dir_name(repo_root: &Path) -> String {
    // Canonicalize so that "." resolves to the real directory name.
    let canonical = repo_root
        .canonicalize()
        .unwrap_or_else(|_| repo_root.to_path_buf());
    canonical
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "unnamed-project".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_creates_structure() {
        let dir = tempfile::tempdir().unwrap();
        run(dir.path(), false).unwrap();

        let cogz = dir.path().join(".cogz");
        assert!(cogz.is_dir());
        assert!(cogz.join("knowledge").is_dir());
        assert!(cogz.join("rules").is_dir());
        assert!(cogz.join("observations").is_dir());
        assert!(cogz.join("config.toml").is_file());
        assert!(cogz.join(".gitignore").is_file());
    }

    #[test]
    fn init_generates_valid_config() {
        let dir = tempfile::tempdir().unwrap();
        run(dir.path(), false).unwrap();

        let config_path = dir.path().join(".cogz/config.toml");
        let config = config::load(&config_path).unwrap();
        // Project name falls back to directory name
        let expected = dir
            .path()
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_string();
        assert_eq!(config.project.name, expected);
    }

    #[test]
    fn init_gitignore_content() {
        let dir = tempfile::tempdir().unwrap();
        run(dir.path(), false).unwrap();

        let gitignore = dir.path().join(".cogz/.gitignore");
        let content = fs::read_to_string(&gitignore).unwrap();
        // Observations are now tracked in git (first-class citizens).
        assert!(!content.contains("observations/"));
        assert!(content.contains("cogz.db"));
        assert!(content.contains("cogz.db-wal"));
        assert!(content.contains("cogz.db-shm"));
    }

    #[test]
    fn init_local_only_gitignore() {
        let dir = tempfile::tempdir().unwrap();
        run(dir.path(), true).unwrap();

        let gitignore = dir.path().join(".cogz/.gitignore");
        let content = fs::read_to_string(&gitignore).unwrap();
        assert!(content.contains("*"));
        assert!(!content.contains("observations/"));
    }

    #[test]
    fn init_refuses_if_already_exists() {
        let dir = tempfile::tempdir().unwrap();
        // First init succeeds
        run(dir.path(), false).unwrap();
        // Second init fails
        let result = run(dir.path(), false);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("already exists"));
    }

    #[test]
    fn detect_from_dir_name_uses_basename() {
        let dir = tempfile::tempdir().unwrap();
        let name = detect_from_dir_name(dir.path());
        let expected = dir
            .path()
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_string();
        assert_eq!(name, expected);
    }

    #[test]
    fn detect_from_git_remote_returns_none_outside_repo() {
        let dir = tempfile::tempdir().unwrap();
        assert!(detect_from_git_remote(dir.path()).is_none());
    }
}
